# This is an example configuration file for EPAB.
# 
# Version: 2018.9.2.4.
# 
# WARNING: this example file will be overwritten every time EPAB starts. Make sure to save your work under another 
# name!
# 
# It must be renamed to "pyproject.toml" in order to come into effect.
# 
# The configuration file follows the TOML format specification.
# 
# Mandatory and optional values
# =============================
# 
# Some values are mandatory, some aren't. Mandatory values are marked with the "MANDATORY VALUE" tag. If mandatory values
# are missing, EPAB will not start.
# 
# Note that, while not necessary for EPAB to function, failing to provide non-mandatory values may prevent 
# non-essential modules to start.
# 
# OS environment
# ==============
# 
# All configuration values may also be given using the OS environment instead of the config file. However, 
# the "EPAB_" prefix must be added (this is to prevent any potential conflict with other application.
# 
# For example, the configuration "dummy_key: dummy_value" would be set in the OS environment using the variable
# "EPAB_DUMMY_KEY=dummy_value".
# 
# Values types
# =============
# 
# Value types will be checked at runtime.
# 
# TOML specification
# ==================
# 
# The full TOML specification can be found at: 
# 
# Here's an example taken from the readme:
# 
# ####################################################################
# # This is a TOML document.
# 
# title = "TOML Example"
# 
# [owner]
# name = "Tom Preston-Werner"
# dob = 1979-05-27T07:32:00-08:00 # First class dates
# 
# [database]
# server = "192.168.1.1"
# ports = [ 8001, 8001, 8002 ]
# connection_max = 5000
# enabled = true
# 
# [servers]
# 
#   # Indentation (tabs and/or spaces) is allowed but not required
#   [servers.alpha]
#   ip = "10.0.0.1"
#   dc = "eqdc10"
# 
#   [servers.beta]
#   ip = "10.0.0.2"
#   dc = "eqdc10"
# 
# [clients]
# data = [ ["gamma", "delta"], [1, 2] ]
# 
# # Line breaks are OK when inside arrays
# hosts = [
#   "alpha",
#   "omega"
# ]
# ####################################################################
#
#
# START OF ACTUAL CONFIG FILE


[tool.epab]
# Package name
# value type: string
# MANDATORY CONFIG VALUE
package_name = "esst"

# Less console output
# value type: boolean
# This configuration is optional and comes with a default setting
# default: False
# quiet = 

# More console output
# value type: boolean
# This configuration is optional and comes with a default setting
# default: False
# verbose = 


[tool.epab.changelog]
# Disable changelog building
# value type: boolean
# This configuration is optional and comes with a default setting
# default: False
# disable = 

# Path to changelog file
# value type: path
# This configuration is optional and comes with a default setting
# default: CHANGELOG.rst
# file_path = 


[tool.epab.test]
# Additional options for test run
# value type: string
# This configuration is optional and comes with a default setting
# default: 
# runner_options = 

# Amount of \slow\ tests to show
# value type: integer
# This configuration is optional and comes with a default setting
# default: 10
# duration_count = 

# Target of pytest
# value type: string
# This configuration is optional and comes with a default setting
# default: test
# target = 

# Minimal coverage to pass tests
# value type: integer
# This configuration is optional and comes with a default setting
# default: 20
# coverage_fail_under = 

# Timeout in seconds for pytest runner
# value type: integer
# This configuration is optional and comes with a default setting
# default: 300
# timeout = 


[tool.epab.lint]
# Linter max line width
# value type: integer
# This configuration is optional and comes with a default setting
# default: 120
# line_length = 

# List of comma separated files for flake8 to exclude
# value type: string
# This configuration is optional and comes with a default setting
# default: 
# flake8_exclude = 

# Additional MyPy arguments
# value type: string
# This configuration is optional and comes with a default setting
# default: 
# mypy_args = 


[tool.epab.freeze]
# Main entry point for pyinstaller
# value type: string
# This configuration is optional and comes with a default setting
# default: 
entry_point = "esst/__main__.py"

# PyInstaller data-files list
# value type: List of strings
# This configuration is optional and comes with a default setting
# default: []
# data_files = 


[tool.epab.doc]
# Documentation repository on Github
# value type: string
# This configuration is optional and comes with a default setting
# default: 
# repo = 

# Local documentation directory
# value type: path
# This configuration is optional and comes with a default setting
# default: ./doc
# folder = 


[tool.epab.appveyor]
# Additional command line options for tests run on AV
# value type: string
# This configuration is optional and comes with a default setting
# default: --long
# test_runner_options = 

# List of artifacts for Appveyor
# value type: List of strings
# This configuration is optional and comes with a default setting
# default: []
# artifacts = 


[tool.epab.qt]
# Qt resource file (.qrc) location
# value type: string
# This configuration is optional and comes with a default setting
# default: 
# res_src = 

# Compiled Qt resource file (.py) target location
# value type: string
# This configuration is optional and comes with a default setting
# default: 
# res_tgt = 
